#!/bin/bash
#
# Startup script for the SmartFrog daemon
#
# processname: sfDaemon
# pidfile: /var/run/sfdaemon.pid


# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0

# Set Envrionment
if [[ -f /etc/sysconfig/smartfrog ]]
then
	. /etc/sysconfig/smartfrog
fi

# Add Smartfrog to the path
PATH="$${PATH-}:$${SFHOME}/bin"

# Export the Display Variable
export DISPLAY

ProgName="SmartFrog Daemon"
ProgDir="$$SFHOME/bin"
ProgBin="sfDaemon"
Filename="smartfrogd"
LockFile="/var/lock/subsys/$$ProgBin"
RunFile=/var/run/$$ProgBin.pid
ProgStop="smartfrog -a rootProcess:TERMINATE:::localhost: -e -quietexit"
ProgLog="${rpm.log.dir}/$$Filename.log"

test -x $$ProgDir/$$ProgBin || exit 0


# Change the major init functions into our functions.
start() {     

	# is it already running
	status $$ProgBin >/dev/null 2>&1
	if [ $$? -eq 0 ]; then
	    return 0
	fi;

	echo -n "Starting $$ProgName: "

	ulimit -S -c 0 >/dev/null 2>&1

	echo "" >> $$ProgLog
	echo "---- Starting $$ProgName -----" >> $$ProgLog
	nohup $$ProgDir/$$ProgBin -headless >>$$ProgLog  2>&1 &
	RETVAL=$$?
	if [ $$RETVAL -eq 0 ]; then
	    success
	    touch $$LockFile
	else
	    failure
	    fi;
	echo
	return $$RETVAL
}

stop() {
	echo -n "Stopping $$ProgName: "

	echo "" >> $$ProgLog
	echo "---- Stopping $$ProgName -----" >> $$ProgLog
	$$ProgDir/$$ProgStop >>$$ProgLog 2>&1
	
	RETVAL=$$?
	[ $$RETVAL -eq 0 ] && rm -f $$LockFile $$RunFile
	success
	echo
	return $$RETVAL
}


# See how we were called.
case "$$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	$$ProgDir/sfPing localhost
#	status $$ProgDir/$$ProgBin
	;;
  restart)
	stop
	start
	;;
  *)
	echo $$"Usage: $$PROG {start|stop|restart|status}"
	exit 1
esac

exit $$RETVAL


