/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */
package org.smartfrog.regtest.arithmetic.templategen;

public interface CalculatorConstants {

  int EOF = 0;
  int NUMBER = 5;
  int DIGIT = 6;
  int GENERATOR = 7;
  int TERMINATOR = 8;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"G\"",
    "\"T\"",
    "\"+\"",
    "\"*\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
  };

}
