/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_smartfrog_services_dependencies_experimental_modelcheck_NuSMVInterface */

#ifndef _Included_org_smartfrog_services_dependencies_experimental_modelcheck_NuSMVInterface
#define _Included_org_smartfrog_services_dependencies_experimental_modelcheck_NuSMVInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_smartfrog_services_dependencies_experimental_modelcheck_NuSMVInterface
 * Method:    run
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_smartfrog_services_dependencies_experimental_modelcheck_NuSMVInterface_run
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
