#!/bin/sh

if [ -z "$SFHOME" -o ! -d "$SFHOME" ] ; then
    #echo "$0"
    SFHOME=`dirname "$0"`/..
    SFHOME=`cd "$SFHOME" && pwd`
    export SFHOME;
    echo SFHOME undefined, using $SFHOME as base directory;
fi

cd "$SFHOME"
cd test
rm ./log/*.log
rm ./log/*.out

export SFDEFAULTINI=-Dorg.smartfrog.iniFile="$SFHOME/test/default.ini"

echo "Start Daemon"

"$SFHOME/bin/sfDaemon" &

sleep 5s

echo "Run test" 
"$SFHOME/bin/smartfrog" -f org/smartfrog/examples/configurationdescriptor/example.sfcd -e &

sleep 45s

echo "Stop Daemon" 
"$SFHOME/bin/sfStopDaemon" localhost

echo "Test finished, logs in $SFHOME/test/log"

wait