

/*
 * Created on Tue Jun 10 05:25:03 IST 2008
 *
 * Generated by GEMS 
 */
 
package org.smartfrog.authoringtool;



import org.gems.designer.metamodel.gen.AttributeInfo;
import org.gems.designer.model.AttributeValidator;
import org.gems.designer.ModelProvider;
import org.gems.designer.ModelRepository;
import org.gems.designer.model.Visitor;
import org.gems.designer.model.ConnectionType;
import org.gems.designer.model.Wire;
import org.eclipse.ui.views.properties.IPropertyDescriptor;

import java.util.Vector;
import org.gems.designer.model.ModelObject;
import org.gems.designer.model.LogicElement;
import java.util.List;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.draw2d.geometry.Dimension;
import org.eclipse.draw2d.geometry.Point;
import org.gems.designer.model.ModelUtilities;
import org.gems.designer.model.props.CustomProperty;
import org.gems.designer.model.props.CustomPropertyEx;
import org.gems.designer.model.props.PropertyRepository;
import org.eclipse.emf.ecore.EObject;
import org.smartfrog.authoringtool.emf.*;

public class Composite extends org.gems.designer.model.LinkedModel  implements Adapter, EMFModelObject, org.gems.designer.model.EMFModelElement{

	private org.smartfrog.authoringtool.emf.Composite model_;
	private Notifier target_;
	
	public Composite(){		
	}
	
	public Composite(org.smartfrog.authoringtool.emf.Composite model){
		model_ = model;
		super.setName(model_.getName());
		super.setID(model_.getId());
    	model_.eAdapters().add(this);
	}
	
	public org.smartfrog.authoringtool.emf.Composite getModel(){
		if(model_ == null){
			model_ = org.smartfrog.authoringtool.emf.impl.SmartfrogFactoryImpl.eINSTANCE.createComposite();
			super.setName(model_.getName());
			model_.eAdapters().add(this);
		}
		return model_;
	}
	
	public org.smartfrog.authoringtool.emf.Composite getExtendedModel(){
		return getModel();
	}
	
	public org.smartfrog.authoringtool.emf.Composite getEMFObject(){
		return getModel();
	}
	
       
    public String getName(){
    	return getExtendedModel().getName();
    }
    
    public boolean isVisible(){
    	return getExtendedModel().isVisible();
    }
    
    
    public void setVisible(boolean b){
    	getExtendedModel().setVisible(b);
    	super.setVisible(b);
    }
    
    public void setName(String name){
    	getExtendedModel().setName(name);
    	super.setName(name);
    }
    
    public String getID(){
    	return getExtendedModel().getId();
    }
    
    public boolean isSubtype(){
    	return getExtendedModel().isSubtype();
    }
    
    public void setSubtype(boolean b){
    	getExtendedModel().setSubtype(b);
    	super.setSubtype(b);
    }
    
    public void setID(String id){
    	getExtendedModel().setId(id);
    	super.setID(id);
    }
    
    public Point getLocation(){
    	return new Point(getExtendedModel().getX(),getExtendedModel().getY());
    }
    
    public void setLocation(Point p) {
    	getExtendedModel().setX(p.x);
    	getExtendedModel().setY(p.y);
        super.setLocation(p);
    }
    
    public Dimension getSize() {
        return new Dimension(getExtendedModel().getWidth(),getExtendedModel().getHeight());
    }
    
    public org.gems.designer.Subtype createSubtype(){
    	return new EMFSubtypeImpl(this,getName());
    }
    
    public void setSize(Dimension d){
    	getExtendedModel().setWidth(d.width);
    	getExtendedModel().setHeight(d.height);
    	super.setSize(d);
    }
    
    public EObject getEMFModelElement(){
    	return getEMFObject();
    }
    
    public String getModelLinkTarget(){
    	return getExtendedModel().getModelLinkTarget();
    }
    
    public void setModelLinkTarget(String target){
    	getExtendedModel().setModelLinkTarget(target);
 		super.setModelLinkTarget(target);
    }
    	
    	public Notifier getTarget() {
    		return target_;
    	}
    	
    	public void setTarget(Notifier newTarget) {
    		target_ = newTarget;
    	}
    	
    	public boolean isAdapterForType(Object type) {
    		return getModel() == type;
    	}
    
    
    

    public static final IPropertyDescriptor[] COMPOSITE_ATTRIBUTE_DESCRIPTORS =
    {
    };
    public static final Object[] COMPOSITE_DEFAULT_ATTRIBUTE_VALUES = {
       
    };
    
      	 

    
    protected void getPropertyDescriptors(Vector desc){
    	desc.addAll(java.util.Arrays.asList(COMPOSITE_ATTRIBUTE_DESCRIPTORS));    	
    	super.getPropertyDescriptors(desc);
    }
    
   
    	
    public String findAttributeType(String attr){
      return super.findAttributeType(attr);
    }
    public Object getAttribute(String attr){
    	
     return super.getAttribute(attr);
   }
  
   
    public void setAttribute(String attr, Object val){
         if(attr != null){
           AttributeValidator validator = AttributeValidators.getInstance().getValidator(attr);
           if(validator != null &&
              !validator.validValue(this,attr,val)){
                return;
              }
         }	
         if(attr.equals(org.gems.designer.model.Atom.NAME)){
        	 getModel().setName((String)val);
         }   													
        super.setAttribute(attr,val);
   }
   
   public void notifyChanged(Notification notification) {
   		int type = notification.getEventType();
   		int featureId = notification.getFeatureID(SmartfrogPackage.class);
    		
   		switch(type) {
   		case Notification.SET:
   		
   		case Notification.ADD:
   		case Notification.REMOVE:
   		}
   }
   
    

	
	
		







public void connectInput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.connectInput(w);
	else
		connectInput(w);
}

public void disconnectInput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.disconnectInput(w);
	else
		disconnectInput(w);
}



public void connectOutput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.connectOutput(w);
	else
		connectOutput(w);
}

public void disconnectOutput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.disconnectOutput(w);
	else
		disconnectOutput(w);
}



    
    
    public String getConnectionRole(ConnectionType ct, boolean src){
	
	  return super.getConnectionRole(ct,src);
	}
	
	public List<String> getRelationshipRoles(){
    	java.util.List<String> roles = super.getRelationshipRoles();
    	
    	return roles;
    }
	
	
	public ConnectionType getConnectionTypeForRole(String role){
	
	  return super.getConnectionTypeForRole(role);
	}
	
    public Object getRoleValue(String role){
	
	
		if("ChildComposite".equalsIgnoreCase(role)){
	       return getChildComposite();
	    }
	
		if("Composites".equalsIgnoreCase(role)){
	       return getComposites();
	    }
	
	
		if("SuperComposite".equalsIgnoreCase(role)){
	       return getSuperComposite();
	    }
	
		if("Components".equalsIgnoreCase(role)){
	       return getComponents();
	    }
	
		if("Compos".equalsIgnoreCase(role)){
	       return getCompos();
	    }
	
		if("Compo".equalsIgnoreCase(role)){
	       return getCompo();
	    }
	
	  return super.getRoleValue(role);
	}
	
	
	public Composite getChildComposite(){
	       if(getParent() instanceof Composite){
	       	  return (Composite)getParent();
	       }
	       return null;
	}
	
	public DependencyModel getComposites(){
	       if(getParent() instanceof DependencyModel){
	       	  return (DependencyModel)getParent();
	       }
	       return null;
	}
	
    
    public boolean isAbstract(){return false;}
     
    public ModelProvider getModelProvider() {
        ModelProvider provider = super.getModelProvider();
        if(provider == null){
        	provider = new SmartfrogProvider();
        	ModelRepository.getInstance().registerModelProvider(provider);
        }
        return provider;
    }
    
    protected void buildContainmentNames() {
        	containmentNames_.put(Composite.class,"SuperComposite");
        	containmentNames_.put("SuperComposite",Composite.class);
        	childContainmentNames_.put(Composite.class,"ChildComposite");
        	containmentNames_.put(Component.class,"Components");
        	containmentNames_.put("Components",Component.class);
        	childContainmentNames_.put(Component.class,"Group_of_components");
        	containmentNames_.put(Attribute.class,"Compos");
        	containmentNames_.put("Compos",Attribute.class);
        	childContainmentNames_.put(Attribute.class,"Composite_arrtibutes");
        	containmentNames_.put(Connectors.class,"Compo");
        	containmentNames_.put("Compo",Connectors.class);
        	childContainmentNames_.put(Connectors.class,"DepConnector");
    }
    
    	public List<String> getContainmentRoles(){
    	List<String> roles = super.getContainmentRoles();
    	
    	roles.add("ChildComposite");
    	
    	roles.add("Composites");
    	
    	return roles;
    }
    
    public Class getParentForRole(String role){
    	
    	if("ChildComposite".equals(role)){
    		return Composite.class;
    	}
    	
    	if("Composites".equals(role)){
    		return DependencyModel.class;
    	}
    	
    	return super.getParentForRole(role);
    }
    
    public String getRoleForParent(Class c){
    	
    	if(Composite.class.isAssignableFrom(c)){
    	   return "ChildComposite";
    	}
    	
    	if(DependencyModel.class.isAssignableFrom(c)){
    	   return "Composites";
    	}
    	
    	return super.getRoleForParent(c);
    }	
    
public void accept(Visitor visitor) {
   if(visitor instanceof SmartfrogVisitor)
   	((SmartfrogVisitor)visitor).visitComposite(this);
   else
     super.accept(visitor);
}
   
    
    public void addChild(LogicElement child, int index) {
       addChild(child,index,true);
    }
    
    public void addChild(LogicElement child, int index, boolean modifymodel) {
       	if(modifymodel){
    	  if(child instanceof Composite){
    	    org.smartfrog.authoringtool.emf.Composite ceobj = ((Composite)child).getEMFObject();
    		getModel().getSuperComposite().add(ceobj);
    		ceobj.setChildComposite(getModel());
    	  }
    	
    	  if(child instanceof Component){
    	    org.smartfrog.authoringtool.emf.Component ceobj = ((Component)child).getEMFObject();
    		getModel().getComponents().add(ceobj);
    		ceobj.setGroup_of_components(getModel());
    	  }
    	
    	  if(child instanceof Attribute){
    	    org.smartfrog.authoringtool.emf.Attribute ceobj = ((Attribute)child).getEMFObject();
    		getModel().getCompos().add(ceobj);
    		ceobj.setComposite_arrtibutes(getModel());
    	  }
    	
    	  if(child instanceof Connectors){
    	    org.smartfrog.authoringtool.emf.Connectors ceobj = ((Connectors)child).getEMFObject();
    		getModel().getCompo().add(ceobj);
    		ceobj.setDepConnector(getModel());
    	  }
    	
    	}
    	
    	super.addChild(child,index);
    	
    }
    
    public void removeChild(LogicElement child){
		removeChild(child,true);
    }
    
    public void removeChild(LogicElement child, boolean modifymodel){
    	if(modifymodel){
     	
    	if(child instanceof Composite){
    	    org.smartfrog.authoringtool.emf.Composite ceobj = ((Composite)child).getEMFObject();
    		getModel().getSuperComposite().remove(ceobj);
    		ceobj.setChildComposite(null);
    	}
    	
    	if(child instanceof Component){
    	    org.smartfrog.authoringtool.emf.Component ceobj = ((Component)child).getEMFObject();
    		getModel().getComponents().remove(ceobj);
    		ceobj.setGroup_of_components(null);
    	}
    	
    	if(child instanceof Attribute){
    	    org.smartfrog.authoringtool.emf.Attribute ceobj = ((Attribute)child).getEMFObject();
    		getModel().getCompos().remove(ceobj);
    		ceobj.setComposite_arrtibutes(null);
    	}
    	
    	if(child instanceof Connectors){
    	    org.smartfrog.authoringtool.emf.Connectors ceobj = ((Connectors)child).getEMFObject();
    		getModel().getCompo().remove(ceobj);
    		ceobj.setDepConnector(null);
    	}
    	
    	}
    	
    		super.removeChild(child);
    	
    }
    
    /**
     * Returns any children of type Composite.class.
     */
    public List<Composite> getSuperComposite(){
    		return (List<Composite>)listChildrenOfType(Composite.class);
    }
    /**
     * Returns any children of type Component.class.
     */
    public List<Component> getComponents(){
    		return (List<Component>)listChildrenOfType(Component.class);
    }
    /**
     * Returns any children of type Attribute.class.
     */
    public List<Attribute> getCompos(){
    		return (List<Attribute>)listChildrenOfType(Attribute.class);
    }
    /**
     * Returns any children of type Connectors.class.
     */
    public List<Connectors> getCompo(){
    		return (List<Connectors>)listChildrenOfType(Connectors.class);
    }
    
    public boolean isExpanded(){
    	return getExtendedModel().isExpanded();
    }
    
    public void setExpanded(boolean ex){
    	getExtendedModel().setExpanded(ex);
    	super.setExpanded(ex);
    }
    
    public Dimension getExpandSize() {
        return new Dimension(getModel().getExpandedWidth(),getModel().getExpandedHeight());
    }
    
    public void setExpandSize(Dimension d){
    	getExtendedModel().setExpandedWidth(d.width);
    	getExtendedModel().setExpandedHeight(d.height);
    	super.setExpandSize(d);
    }
    
    public String getModelID() {
        return SmartfrogProvider.MODEL_ID;
    }
    

}

