  


/*
 * Created on Fri May 30 10:30:10 IST 2008
 *
 * Generated by GEMS 
 */
 
package org.smartfrog.authoringtool;



public interface EMFModelObject {
	public org.smartfrog.authoringtool.emf.ModelObject getEMFObject();
}