

/*
 * Created on Fri May 30 10:30:10 IST 2008
 *
 * Generated by GEMS 
 */
 
package org.smartfrog.authoringtool;


import org.gems.designer.model.Atom;
import org.gems.designer.model.Model;
import org.gems.designer.model.Visitor;

/**
 * 
 */
 
public interface SmartfrogVisitor extends Visitor{
    public static final String MODEL_ID = "http://www.smartfrog.org/sfml";
    
	
	


	   public void visitComponent(Component tovisit);
	 
	   public void visitComposit(Composit tovisit);
	 
	   public void visitDependencyModel(DependencyModel tovisit);
	 
	   public void visitAttribute(Attribute tovisit);
	 
	   public void visitAnd(And tovisit);
	 
	   public void visitConnectors(Connectors tovisit);
	 
	   public void visitOr(Or tovisit);
	 
}

