<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org.smartfrog.authoringtool.emf" nsURI="http://www.smartfrog.org/sfml" nsPrefix="smartfrog">
  
   <eClassifiers xsi:type="ecore:EClass" name="MementoValue">
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="Memento">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
  		 <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="2000"
        eType="#//MementoValue" containment="true"/>
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="Subtype">
   	 <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="AnonymousSubtype"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base" upperBound="1"
        eType="#//ModelObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="2000"
        eType="#//ModelObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="20000"
        eType="#//SubtypeLink" containment="true"/>
   </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SubtypeLink">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base" upperBound="1"
        eType="#//ModelObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instance" upperBound="1"
        eType="#//ModelObject"/>
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="ModelObject">
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="X" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="Y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="Width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="100"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="Height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="100"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExpandedWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="200"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExpandedHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="200"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="Expanded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="Subtype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="Visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModelLinkTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
     
 <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Connectors">
  </eClassifiers>

     
 <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//Connectors">
  </eClassifiers>

     
 <eClassifiers xsi:type="ecore:EClass" name="Nor" eSuperTypes="#//Connectors">
  </eClassifiers>

     
 <eClassifiers xsi:type="ecore:EClass" name="Nand" eSuperTypes="#//Connectors">
  </eClassifiers>

     
 <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Extends" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Component_Attribute_Container" upperBound="2000"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Child_Components" upperBound="1"
        eType="#//Composite" containment="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Model_Member_Components" upperBound="1"
        eType="#//DependencyModel" containment="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Simple_Dependent_Source" lowerBound="0" upperBound="2147483647"
        eType="#//SimpleDependencyConnection" />
      <eStructuralFeatures xsi:type="ecore:EReference" name="Component_Dependent_Source" lowerBound="0" upperBound="2147483647"
        eType="#//InputDependencyConnection" />
      <eStructuralFeatures xsi:type="ecore:EReference" name="Simple_Depend_On" lowerBound="1" upperBound="1"
        eType="#//SimpleDependencyConnection" />
      <eStructuralFeatures xsi:type="ecore:EReference" name="Connector_Depend_On_Component" lowerBound="0" upperBound="2147483647"
        eType="#//OutputDependencyConnection" />
  </eClassifiers>

     
 <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SuperComposite" upperBound="2000"
        eType="#//Composite" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Composite_Component_Container" upperBound="2000"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Composite_Attribute_Container" upperBound="2000"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Composite_Connector_Container" upperBound="2000"
        eType="#//Connectors" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ChildComposite" upperBound="1"
        eType="#//Composite" containment="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Model_Member_Composites" upperBound="1"
        eType="#//DependencyModel" containment="false"/>
  </eClassifiers>

     
 <eClassifiers xsi:type="ecore:EClass" name="DependencyModel" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Run" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Model_composite_Container" upperBound="2000"
        eType="#//Composite" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Model_Component_Container" upperBound="2000"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Model_Connector_Container" upperBound="2000"
        eType="#//Connectors" containment="true"/>
  </eClassifiers>

     
 <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StateData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StateListen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StateNotify" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsLazyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Component_Attribute" upperBound="1"
        eType="#//Component" containment="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Composite_Arrtibute" upperBound="1"
        eType="#//Composite" containment="false"/>
  </eClassifiers>

     
 <eClassifiers xsi:type="ecore:EClass" name="Connectors" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Child_Connector" upperBound="1"
        eType="#//Composite" containment="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Member_Connector" upperBound="1"
        eType="#//DependencyModel" containment="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Connector_Dependent_Source" lowerBound="0" upperBound="2147483647"
        eType="#//OutputDependencyConnection" />
      <eStructuralFeatures xsi:type="ecore:EReference" name="Component_Depends_On_Connector" lowerBound="0" upperBound="2147483647"
        eType="#//InputDependencyConnection" />
  </eClassifiers>

     
 <eClassifiers xsi:type="ecore:EClass" name="SimpleDependencyConnection">
 	 <eStructuralFeatures xsi:type="ecore:EReference" name="Source" eType="#//Component"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="Target" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Relevant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dependency_Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
  </eClassifiers>

     
 <eClassifiers xsi:type="ecore:EClass" name="InputDependencyConnection">
 	 <eStructuralFeatures xsi:type="ecore:EReference" name="Source" eType="#//Component"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="Target" eType="#//Connectors"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Relevant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Input_Dependency_Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
  </eClassifiers>

     
 <eClassifiers xsi:type="ecore:EClass" name="OutputDependencyConnection">
 	 <eStructuralFeatures xsi:type="ecore:EReference" name="Source" eType="#//Connectors"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="Target" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Relevant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Output_Dependency_Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Root">
  	<eStructuralFeatures xsi:type="ecore:EReference" name="mementos" upperBound="2000"
        eType="#//Memento" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtypes" upperBound="2000"
        eType="#//Subtype" containment="true"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="RealRoot" upperBound="1"
        eType="#//DependencyModel" containment="true"/>
   
     <eStructuralFeatures xsi:type="ecore:EReference" name="And" upperBound="2000"
        eType="#//And" containment="true"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="Or" upperBound="2000"
        eType="#//Or" containment="true"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="Nor" upperBound="2000"
        eType="#//Nor" containment="true"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="Nand" upperBound="2000"
        eType="#//Nand" containment="true"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="Component" upperBound="2000"
        eType="#//Component" containment="true"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="Composite" upperBound="2000"
        eType="#//Composite" containment="true"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="DependencyModel" upperBound="2000"
        eType="#//DependencyModel" containment="true"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="Attribute" upperBound="2000"
        eType="#//Attribute" containment="true"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="Connectors" upperBound="2000"
        eType="#//Connectors" containment="true"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="SimpleDependencyConnection" upperBound="2000"
        eType="#//SimpleDependencyConnection" containment="true"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="InputDependencyConnection" upperBound="2000"
        eType="#//InputDependencyConnection" containment="true"/>
     <eStructuralFeatures xsi:type="ecore:EReference" name="OutputDependencyConnection" upperBound="2000"
        eType="#//OutputDependencyConnection" containment="true"/>
      
  </eClassifiers>

</ecore:EPackage>