

/*
 * Created on Wed Jun 25 18:58:26 IST 2008
 *
 * Generated by GEMS 
 */
 
package org.smartfrog.authoringtool;



import org.gems.designer.metamodel.gen.AttributeInfo;
import org.gems.designer.model.AttributeValidator;
import org.gems.designer.ModelProvider;
import org.gems.designer.ModelRepository;
import org.gems.designer.model.Visitor;
import org.gems.designer.model.ConnectionType;
import org.gems.designer.model.Wire;
import org.eclipse.ui.views.properties.IPropertyDescriptor;

import java.util.Vector;
import org.gems.designer.model.ModelObject;
import org.gems.designer.model.LogicElement;
import java.util.List;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.draw2d.geometry.Dimension;
import org.eclipse.draw2d.geometry.Point;
import org.gems.designer.model.ModelUtilities;
import org.gems.designer.model.props.CustomProperty;
import org.gems.designer.model.props.CustomPropertyEx;
import org.gems.designer.model.props.PropertyRepository;
import org.eclipse.emf.ecore.EObject;
import org.smartfrog.authoringtool.emf.*;

public class DependencyModel extends org.gems.designer.model.LinkedModel  implements Adapter, EMFModelObject, org.gems.designer.model.EMFModelElement{

	private org.smartfrog.authoringtool.emf.DependencyModel model_;
	private Notifier target_;
	
	public DependencyModel(){		
	}
	
	public DependencyModel(org.smartfrog.authoringtool.emf.DependencyModel model){
		model_ = model;
		super.setName(model_.getName());
		super.setID(model_.getId());
    	model_.eAdapters().add(this);
	}
	
	public org.smartfrog.authoringtool.emf.DependencyModel getModel(){
		if(model_ == null){
			model_ = org.smartfrog.authoringtool.emf.impl.SmartfrogFactoryImpl.eINSTANCE.createDependencyModel();
			super.setName(model_.getName());
			model_.eAdapters().add(this);
		}
		return model_;
	}
	
	public org.smartfrog.authoringtool.emf.DependencyModel getExtendedModel(){
		return getModel();
	}
	
	public org.smartfrog.authoringtool.emf.DependencyModel getEMFObject(){
		return getModel();
	}
	
       
    public String getName(){
    	return getExtendedModel().getName();
    }
    
    public boolean isVisible(){
    	return getExtendedModel().isVisible();
    }
    
    
    public void setVisible(boolean b){
    	getExtendedModel().setVisible(b);
    	super.setVisible(b);
    }
    
    public void setName(String name){
    	getExtendedModel().setName(name);
    	super.setName(name);
    }
    
    public String getID(){
    	return getExtendedModel().getId();
    }
    
    public boolean isSubtype(){
    	return getExtendedModel().isSubtype();
    }
    
    public void setSubtype(boolean b){
    	getExtendedModel().setSubtype(b);
    	super.setSubtype(b);
    }
    
    public void setID(String id){
    	getExtendedModel().setId(id);
    	super.setID(id);
    }
    
    public Point getLocation(){
    	return new Point(getExtendedModel().getX(),getExtendedModel().getY());
    }
    
    public void setLocation(Point p) {
    	getExtendedModel().setX(p.x);
    	getExtendedModel().setY(p.y);
        super.setLocation(p);
    }
    
    public Dimension getSize() {
        return new Dimension(getExtendedModel().getWidth(),getExtendedModel().getHeight());
    }
    
    public org.gems.designer.Subtype createSubtype(){
    	return new EMFSubtypeImpl(this,getName());
    }
    
    public void setSize(Dimension d){
    	getExtendedModel().setWidth(d.width);
    	getExtendedModel().setHeight(d.height);
    	super.setSize(d);
    }
    
    public EObject getEMFModelElement(){
    	return getEMFObject();
    }
    
    public String getModelLinkTarget(){
    	return getExtendedModel().getModelLinkTarget();
    }
    
    public void setModelLinkTarget(String target){
    	getExtendedModel().setModelLinkTarget(target);
 		super.setModelLinkTarget(target);
    }
    	
    	public Notifier getTarget() {
    		return target_;
    	}
    	
    	public void setTarget(Notifier newTarget) {
    		target_ = newTarget;
    	}
    	
    	public boolean isAdapterForType(Object type) {
    		return getModel() == type;
    	}
    
    
    

    public static final IPropertyDescriptor[] DEPENDENCYMODEL_ATTRIBUTE_DESCRIPTORS =
    {
new org.eclipse.ui.views.properties.TextPropertyDescriptor("Run","Run")


    };
    public static final Object[] DEPENDENCYMODEL_DEFAULT_ATTRIBUTE_VALUES = {
       
            new Boolean(true)
    };
    
      	 

    
    protected void getPropertyDescriptors(Vector desc){
    	desc.addAll(java.util.Arrays.asList(DEPENDENCYMODEL_ATTRIBUTE_DESCRIPTORS));    	
    	super.getPropertyDescriptors(desc);
    }
    
   
    	
    	private Boolean Run_ = new Boolean(true);
    public String findAttributeType(String attr){
      if(attr.equals("Run")){
        return BOOLEAN_MTYPE;
      }
      return super.findAttributeType(attr);
    }
   public Boolean getRun(){
   	return getModel().isRun();
   	
   }
   public void setRun(Boolean val){
     Object old = getRun();
   	 getModel().setRun(val);
   	 
   	  Object[] valuepair = {"Run",old};        
      org.gems.designer.model.event.ModelChangeEvent event = new org.gems.designer.model.event.ModelChangeEvent(this,
                org.gems.designer.model.event.ModelChangeEvent.ELEMENT_ATTRIBUTE_CHANGED,false,(Object)valuepair);
      org.gems.designer.model.event.ModelEventDispatcher.dispatch(event);
      
      if(event.vetoed()){
      	setRun((Boolean)old);
      }
   }
    public Object getAttribute(String attr){
    	
	 if(attr != null &&
	    attr.equals("Run")){
	    return getRun().toString();
	  }
     return super.getAttribute(attr);
   }
  
   
    public void setAttribute(String attr, Object val){
         if(attr != null){
           AttributeValidator validator = AttributeValidators.getInstance().getValidator(attr);
           if(validator != null &&
              !validator.validValue(this,attr,val)){
                return;
              }
         }	
         if(attr.equals(org.gems.designer.model.Atom.NAME)){
        	 getModel().setName((String)val);
         }   													
	 if(attr != null &&
	    attr.equals("Run")){
	    setRun(new Boolean((String)val));
	  }
      else {
        super.setAttribute(attr,val); }
   }
   
   public void notifyChanged(Notification notification) {
   		int type = notification.getEventType();
   		int featureId = notification.getFeatureID(SmartfrogPackage.class);
    		
   		switch(type) {
   		case Notification.SET:
   		
   			switch(featureId) {
    			case SmartfrogPackage.DEPENDENCY_MODEL__RUN :
   				firePropertyChange(ATTRIBUTE_PREFIX+"Run", notification.getOldBooleanValue(), notification.getNewBooleanValue());
   				break;
   			}
   	    
   		case Notification.ADD:
   		case Notification.REMOVE:
   		}
   }
   
    

	
	
		







public void connectInput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.connectInput(w);
	else
		connectInput(w);
}

public void disconnectInput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.disconnectInput(w);
	else
		disconnectInput(w);
}



public void connectOutput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.connectOutput(w);
	else
		connectOutput(w);
}

public void disconnectOutput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.disconnectOutput(w);
	else
		disconnectOutput(w);
}



    
    
    public String getConnectionRole(ConnectionType ct, boolean src){
	
	  return super.getConnectionRole(ct,src);
	}
	
	public List<String> getRelationshipRoles(){
    	java.util.List<String> roles = super.getRelationshipRoles();
    	
    	return roles;
    }
	
	
	public ConnectionType getConnectionTypeForRole(String role){
	
	  return super.getConnectionTypeForRole(role);
	}
	
    public Object getRoleValue(String role){
	
	
	
		if("Model_composite_Container".equalsIgnoreCase(role)){
	       return getModel_composite_Container();
	    }
	
		if("Model_Component_Container".equalsIgnoreCase(role)){
	       return getModel_Component_Container();
	    }
	
		if("Model_Connector_Container".equalsIgnoreCase(role)){
	       return getModel_Connector_Container();
	    }
	
	  return super.getRoleValue(role);
	}
	
	
    
    public boolean isAbstract(){return false;}
     
    public ModelProvider getModelProvider() {
        ModelProvider provider = super.getModelProvider();
        if(provider == null){
        	provider = new SmartfrogProvider();
        	ModelRepository.getInstance().registerModelProvider(provider);
        }
        return provider;
    }
    
    protected void buildContainmentNames() {
        	containmentNames_.put(Composite.class,"Model_composite_Container");
        	containmentNames_.put("Model_composite_Container",Composite.class);
        	childContainmentNames_.put(Composite.class,"Model_Member_Composites");
        	containmentNames_.put(Component.class,"Model_Component_Container");
        	containmentNames_.put("Model_Component_Container",Component.class);
        	childContainmentNames_.put(Component.class,"Model_Member_Components");
        	containmentNames_.put(Connectors.class,"Model_Connector_Container");
        	containmentNames_.put("Model_Connector_Container",Connectors.class);
        	childContainmentNames_.put(Connectors.class,"Member_Connector");
    }
    
    	public List<String> getContainmentRoles(){
    	List<String> roles = super.getContainmentRoles();
    	
    	return roles;
    }
    
    public Class getParentForRole(String role){
    	
    	return super.getParentForRole(role);
    }
    
    public String getRoleForParent(Class c){
    	
    	return super.getRoleForParent(c);
    }	
    
public void accept(Visitor visitor) {
   if(visitor instanceof SmartfrogVisitor)
   	((SmartfrogVisitor)visitor).visitDependencyModel(this);
   else
     super.accept(visitor);
}
   
    
    public void addChild(LogicElement child, int index) {
       addChild(child,index,true);
    }
    
    public void addChild(LogicElement child, int index, boolean modifymodel) {
       	if(modifymodel){
    	  if(child instanceof Composite){
    	    org.smartfrog.authoringtool.emf.Composite ceobj = ((Composite)child).getEMFObject();
    		getModel().getModel_composite_Container().add(ceobj);
    		ceobj.setModel_Member_Composites(getModel());
    	  }
    	
    	  if(child instanceof Component){
    	    org.smartfrog.authoringtool.emf.Component ceobj = ((Component)child).getEMFObject();
    		getModel().getModel_Component_Container().add(ceobj);
    		ceobj.setModel_Member_Components(getModel());
    	  }
    	
    	  if(child instanceof Connectors){
    	    org.smartfrog.authoringtool.emf.Connectors ceobj = ((Connectors)child).getEMFObject();
    		getModel().getModel_Connector_Container().add(ceobj);
    		ceobj.setMember_Connector(getModel());
    	  }
    	
    	}
    	
    	super.addChild(child,index);
    	
    }
    
    public void removeChild(LogicElement child){
		removeChild(child,true);
    }
    
    public void removeChild(LogicElement child, boolean modifymodel){
    	if(modifymodel){
     	
    	if(child instanceof Composite){
    	    org.smartfrog.authoringtool.emf.Composite ceobj = ((Composite)child).getEMFObject();
    		getModel().getModel_composite_Container().remove(ceobj);
    		ceobj.setModel_Member_Composites(null);
    	}
    	
    	if(child instanceof Component){
    	    org.smartfrog.authoringtool.emf.Component ceobj = ((Component)child).getEMFObject();
    		getModel().getModel_Component_Container().remove(ceobj);
    		ceobj.setModel_Member_Components(null);
    	}
    	
    	if(child instanceof Connectors){
    	    org.smartfrog.authoringtool.emf.Connectors ceobj = ((Connectors)child).getEMFObject();
    		getModel().getModel_Connector_Container().remove(ceobj);
    		ceobj.setMember_Connector(null);
    	}
    	
    	}
    	
    		super.removeChild(child);
    	
    }
    
    /**
     * Returns any children of type Composite.class.
     */
    public List<Composite> getModel_composite_Container(){
    		return (List<Composite>)listChildrenOfType(Composite.class);
    }
    /**
     * Returns any children of type Component.class.
     */
    public List<Component> getModel_Component_Container(){
    		return (List<Component>)listChildrenOfType(Component.class);
    }
    /**
     * Returns any children of type Connectors.class.
     */
    public List<Connectors> getModel_Connector_Container(){
    		return (List<Connectors>)listChildrenOfType(Connectors.class);
    }
    
    public boolean isExpanded(){
    	return getExtendedModel().isExpanded();
    }
    
    public void setExpanded(boolean ex){
    	getExtendedModel().setExpanded(ex);
    	super.setExpanded(ex);
    }
    
    public Dimension getExpandSize() {
        return new Dimension(getModel().getExpandedWidth(),getModel().getExpandedHeight());
    }
    
    public void setExpandSize(Dimension d){
    	getExtendedModel().setExpandedWidth(d.width);
    	getExtendedModel().setExpandedHeight(d.height);
    	super.setExpandSize(d);
    }
    
    public String getModelID() {
        return SmartfrogProvider.MODEL_ID;
    }
    

}

