  


/*
 * Created on Mon Jun 09 15:18:24 IST 2008
 *
 * Generated by GEMS 
 */
 
package org.smartfrog.authoringtool;



public interface EMFModelObject {
	public org.smartfrog.authoringtool.emf.ModelObject getEMFObject();
}