  


/*
 * Created on Wed Jun 25 18:58:26 IST 2008
 *
 * Generated by GEMS 
 */
 
package org.smartfrog.authoringtool;



public interface EMFModelObject {
	public org.smartfrog.authoringtool.emf.ModelObject getEMFObject();
}