  


/*
 * Created on Tue Jun 10 05:25:03 IST 2008
 *
 * Generated by GEMS 
 */
 
package org.smartfrog.authoringtool;



public interface EMFModelObject {
	public org.smartfrog.authoringtool.emf.ModelObject getEMFObject();
}