

/*
 * Created on Tue Jun 10 05:25:03 IST 2008
 *
 * Generated by GEMS 
 */
 
package org.smartfrog.authoringtool;

import org.gems.designer.Memento;

public class MementoImpl implements Memento {

	private org.smartfrog.authoringtool.emf.Memento model_;
	
	public MementoImpl(){		
	}
	
	public MementoImpl(org.smartfrog.authoringtool.emf.Memento model){
		model_ = model;
	}
	
	public org.smartfrog.authoringtool.emf.Memento getModel(){
		if(model_ == null){
			model_ = org.smartfrog.authoringtool.emf.impl.SmartfrogFactoryImpl.eINSTANCE.createMemento();
		}
		return model_;
	}
	public void setId(String id){
		getModel().setId(id);
	}
	
	public String getId(){
		return getModel().getId();
	}
	
	public void setValue(String name, String value){
		org.smartfrog.authoringtool.emf.MementoValue mv = org.smartfrog.authoringtool.emf.impl.SmartfrogFactoryImpl.eINSTANCE.createMementoValue();
		mv.setName(name);
		mv.setValue(value);
		getModel().getData().add(mv);
	}
	public String getValue(String name){
		for(Object curr : getModel().getData()){
			org.smartfrog.authoringtool.emf.MementoValue mv = (org.smartfrog.authoringtool.emf.MementoValue)curr;
			if(mv.getName().equals(name)){
				return mv.getValue();
			}
		}
		return null;
	}
    
}

