/* Generated By:JavaCC: Do not edit this line. DefaultParserConstants.java */
package org.smartfrog.sfcore.languages.sf;

public interface DefaultParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int SEMICOLON = 13;
  int COMMA = 14;
  int LBRACE = 15;
  int RBRACE = 16;
  int LBRACKET = 17;
  int RBRACKET = 18;
  int REFPARTSEP = 19;
  int NULLPROTO = 20;
  int UNIQUE = 21;
  int EXTENDS = 22;
  int LAZY = 23;
  int ROOT = 24;
  int ATTRIB = 25;
  int THIS = 26;
  int PROPERTY = 27;
  int IPROPERTY = 28;
  int PARENT = 29;
  int HOST = 30;
  int PROCESS = 31;
  int INCLUDE = 32;
  int TRUE = 33;
  int FALSE = 34;
  int WORD = 35;
  int SPECIAL = 36;
  int LETTER = 37;
  int DIGIT = 38;
  int STRING = 39;
  int MULTILINESTRING = 40;
  int INTEGER = 41;
  int FLOAT_BASE = 42;
  int EXPONENT = 43;
  int DOUBLE = 44;
  int LONG = 45;
  int FLOAT = 46;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"NULL\"",
    "\"--\"",
    "\"extends\"",
    "\"LAZY\"",
    "\"ROOT\"",
    "\"ATTRIB\"",
    "\"THIS\"",
    "\"PROPERTY\"",
    "\"IPROPERTY\"",
    "\"PARENT\"",
    "\"HOST\"",
    "\"PROCESS\"",
    "\"#include\"",
    "\"true\"",
    "\"false\"",
    "<WORD>",
    "<SPECIAL>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING>",
    "<MULTILINESTRING>",
    "<INTEGER>",
    "<FLOAT_BASE>",
    "<EXPONENT>",
    "<DOUBLE>",
    "<LONG>",
    "<FLOAT>",
  };

}
