
package org.smartfrog.authoringtool.oawgenerator.utils;

/**
 * Generator utilities that can be invoked from xTend files.
 * 
 * Generated by the GEMS oAW plugin.
 * oAW documentation: http://www.eclipse.org/gmt/oaw/doc/
 */
public class GeneratorUtils {
	public static void log(String message){
		System.out.println("[Generator Log]: " + message);
	}
}