#!/bin/bash
cd cudd-2.4.1.0
make -f Makefile.win
cd ../nusmv/src/sm
echo gcc -g -O2 -mno-cygwin -mwindows -c com_hp_ail_smartfrog_collateOutput.c
gcc -g -O2 -mno-cygwin -mwindows -c com_hp_ail_smartfrog_collateOutput.c
cd ../..
cp configwin.h config.h
make -f Makefile.win
echo gcc -g -O2 -mno-cygwin -mwindows -D __int64="long long" -Iinclude -Iinclude/win32/ -shared -Wl,--add-stdcall-alias -o NuSMVInterface.dll NuSMVInterface.c smMain.o  ./.libs/libnusmv.a src/.libs/libnusmvcore.a -L../cudd-2.4.1.0/lib -lcudd -lcudd_util -lmtr -lst src/sm/com_hp_ail_smartfrog_collateOutput.o
gcc -g -O2 -mno-cygwin -mwindows -D __int64="long long" -I./include -I./include/win32/ -shared -Wl,--add-stdcall-alias -o NuSMVInterface.dll NuSMVInterface.c smMain.o  ./.libs/libnusmv.a src/.libs/libnusmvcore.a -L../cudd-2.4.1.0/lib -lcudd -lcudd_util -lmtr -lst src/sm/com_hp_ail_smartfrog_collateOutput.o
cd ..



